version: '3'
services:
  datastorage-test:
    build:
      context: docker-support/datastorage
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=kitedb
      - POSTGRES_PASSWORD=kitedb
      - TZ=GMT
      - DB_USERNAME=deanonymtest
      - DB_PWD=test